# Generated by Django 5.2.16 on 2026-07-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信'), ('bank', '银行')], max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.FloatField()),
                ('tx_type', models.CharField(default='支出', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('currency', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('cp_account', models.CharField(blank=True, default='', max_length=100)),
                ('cp_bank', models.CharField(blank=True, default='', max_length=200)),
                ('source_channel', models.CharField(max_length=20)),
                ('source_id', models.IntegerField()),
                ('row_hash', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='transactions.tag')),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_tags',
                'unique_together': {('transaction', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(related_name='transactions', through='transactions.TransactionTag', to='transactions.tag'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['platform'], name='transaction_platfor_1b8f54_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['time'], name='transaction_time_94c69c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='transaction_amount_8c918e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_type'], name='transaction_tx_type_fdf43c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['counterparty'], name='transaction_counter_5475b0_idx'),
        ),
    ]
