# Generated by Django 5.2.16 on 2026-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_platform_bank_to_boc'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_45fcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-time', 'platform'], name='transaction_time_669d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-time', 'tx_type'], name='transaction_time_9f6a38_idx'),
        ),
    ]
