# Generated by Django 5.2.16 on 2026-07-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.FloatField()),
                ('tx_type', models.CharField(default='支出', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alipay_transactions',
                'constraints': [models.UniqueConstraint(fields=('time', 'amount', 'counterparty'), name='uq_alipay_tx')],
            },
        ),
        migrations.CreateModel(
            name='BocTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.FloatField()),
                ('tx_type', models.CharField(default='支出', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('currency', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('cp_account', models.CharField(blank=True, default='', max_length=100)),
                ('cp_bank', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boc_transactions',
                'constraints': [models.UniqueConstraint(fields=('time', 'amount', 'counterparty'), name='uq_boc_tx')],
            },
        ),
        migrations.CreateModel(
            name='WechatTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.FloatField()),
                ('tx_type', models.CharField(default='支出', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wechat_transactions',
                'constraints': [models.UniqueConstraint(fields=('time', 'amount', 'counterparty'), name='uq_wechat_tx')],
            },
        ),
    ]
